### PR TITLE
solid: Reimplement Presence using solid-primitives

### PR DESCRIPTION
**Pull request by thetarnav**
This reimplements the Presence component using the [`@solid-primitives/transition-group`](https://github.com/solidjs-community/solid-primitives/tree/main/packages/transition-group#readme) and [`@solid-primitives/refs`](https://github.com/solidjs-community/solid-primitives/tree/main/packages/refs#readme) packages. So that the low-level and likely-to-change implementation details — such as resolving JSX structure, diffing it in a pure computation, and updating a signal with a list of elements to display — can be maintained in a single place and reused in different solid transition libraries *(solid-transiotion-group, solid-flip, etc.)*. Similarly how the transition component in vue gets reused because it is built-in into the framework.
From what I've measured the final bundle size didn't change much even though the implementation of used primitives is less specific. The logic of Presence got simplified a lot though.

### CODE REVIEW

**Comment by davedbase** [comment]
I'm good with this. I don't see a reason not to merge it. I'll hold out on merging because there's a conversation internally in SolidJS core about what to do with solid-transition-group itself. A decision there might impact how this implementation will get merged.

**Comment by davedbase** [comment]
Ok, core decided to download solid-transition-group to solidjs-community instead. I'll merge this in now.

**Comment by davedbase** [comment]
@mattgperry can we get this published? :)

**Comment by mattgperry** [comment]
Done, thats out in `10.6.0` !

**Pull request merged**
