### PR TITLE
Update solid package and playground to 1.6

### PR DESCRIPTION
**Pull request by thetarnav**
- Adds gitpod.yml file from #146 (still using gitpod)
- Bumps the solid-js peerDependency to ^1.5.0 — #138 makes a fix targeting solid 1.5, which will cause the previous versions to have a wrong behavior
- Updates @solid-primitives/props dependency
- Updates dev deps
- Adjusts tests for solid 1.6
- Updates solid playground to latest solid-start

### CODE REVIEW

**Comment by davedbase** [comment]
@mattgperry do you mind if we merge this?

**Comment by davedbase** [comment]
I didn't see any issue with merging it myself. Wondering when the next release can go up :)

**Comment by mattgperry** [comment]
Attempting to publish but, when I run `yarn test` with these changes, the process just hangs?

**Comment by thetarnav** [comment]
`solid` runs fine for me
but it crashes on the `dom` package
also, it might be better to exclude `/playgrounds` from tests/build
```
"test": "turbo run test --filter=!./playgrounds/*"
```

**Comment by mattgperry** [comment]
Ah yeah that was a good call, it's all published now thanks!

**Pull request merged**
