### PR TITLE
Qwik Adapter

### PR DESCRIPTION
**Pull request by brunocrosier**

### CODE REVIEW

**Comment by brunocrosier** [comment]
I've published this here if anybody would like to test it out https://www.npmjs.com/package/motion-qwik-adapter

You can also test it out within the `playgrounds/qwik` directory of this repo

**Comment by brunocrosier** [comment]
Any chance we could get this reviewed / merged please @mattgperry ? 🙏🏼

**Comment by thejackshelton** [comment]
What ever happened to this? @mattgperry @thetarnav @davedbase

**Comment by davedbase** [comment]
That's a question better suited for @brunocrosier. My focus has been mostly on the Solid integration.

**Comment by brunocrosier** [comment]
> What ever happened to this? @mattgperry @thetarnav @davedbase

out of my control unfortunately, I'm not a maintainer

**Comment by NachoVazquez** [comment]
> I've published this here if anybody would like to test it out https://www.npmjs.com/package/motion-qwik-adapter
> 
> You can also test it out within the `playgrounds/qwik` directory of this repo

I was preparing myself mentally to do this. 

Someone give this guy a Qwik Hero title if he doesn't already have it.

**Comment by NachoVazquez** [comment]
Are you planning on implementing `Presence`?

**Comment by brunocrosier** [comment]
> Are you planning on implementing `Presence`?

I tried and wasn't able to - I think it might be impossible because of how Qwik handles `Slot`s (but happy to be proved wrong!)

Unfortunately for some reason this PR wasn't merged so I've kind of given up on it

**Comment by Mo0nbase** [comment]
Any reason this wasn't merged @mattgperry? Would be an awesome addition for all us Qwik users!

**Comment by pegak** [comment]
I would really love to have it. Can we do something to merge it? :O

**Comment by mattgperry** [comment]
Yep sorry for the lack of communication, just had our firstborn so been taking care of him! I’m also a bit split what to do here, I overreached with the Solid/Vue integrations and haven’t been able to support them as I’d like. I’m leaning towards splitting them out onto their own repos/packages to whoever wants to keep them maintained and that’d include the Qwik integration.

**Comment by NachoVazquez** [comment]
> Yep sorry for the lack of communication, just had our firstborn so been taking care of him! I’m also a bit split what to do here, I overreached with the Solid/Vue integrations and haven’t been able to support them as I’d like. I’m leaning towards splitting them out onto their own repos/packages to whoever wants to keep them maintained and that’d include the Qwik integration.

Congrats on becoming a parent!

**Comment by pegak** [comment]
Congrats. :)

PS: I think that the Qwik community is active, so it could work.

**Comment by davedbase** [comment]
> Yep sorry for the lack of communication, just had our firstborn so been taking care of him! I’m also a bit split what to do here, I overreached with the Solid/Vue integrations and haven’t been able to support them as I’d like. I’m leaning towards splitting them out onto their own repos/packages to whoever wants to keep them maintained and that’d include the Qwik integration.

Congrats on the firstborn!

@thetarnav and I are striving to support the Solid version as must as possible. Separating it into their own packages makes sense. Will you continue maintaining the core?

**Comment by mattgperry** [comment]
@davedbase Yeah I will do

**Comment by brandonpittman** [comment]
The README for this package makes it look like it's an official package.

https://www.npmjs.com/package/motion-qwik-adapter

**Comment by brunocrosier** [comment]
> The README for this package makes it look like it's an official package.
> 
> https://www.npmjs.com/package/motion-qwik-adapter

https://github.com/motiondivision/motionone/pull/185#issuecomment-1509707116

**Comment by mattgperry** [comment]
Closing re: https://github.com/motiondivision/motionone/discussions/241

**Pull request closed without merging**
